### ISSUE TITLE
weewxd: rtcrthread: Unexpected exception of type <type 'exceptions.KeyError'>

### ISSUE THREAD

**Issue by jkhuon** [gjr80/weewx-realtime_clientraw#4]
This seems to be occurring at midnight...

```
Jun  5 00:00:05 Service1 weewxd: rtcrthread: Unexpected exception of type <type 'exceptions.KeyError'>
...
Jun 11 00:00:01 Service1 weewxd: rtcrthread: Unexpected exception of type <type 'exceptions.KeyError'>
```

It then kills rtctrthread and I have to restart weewx.

**Comment by gjr80** [comment]
What version of WeeWX and `rtcr.py`? If WeeWX v4.x you might want to try the updating `rtcr.py` as per my instructions in my last post in issue #3.

**Comment by jkhuon** [comment]
```
Jun 11 00:05:27 Service1 weewx[19057] INFO __main__: Initializing weewx version 4.1.1
Jun 11 00:05:27 Service1 weewx[19057] INFO __main__: Using Python 2.7.17 (default, Apr 15 2020, 17:20:14) #012[GCC 7.5.0]
Jun 11 00:05:27 Service1 weewx[19057] INFO __main__: Platform Linux-4.15.0-101-generic-x86_64-with-Ubuntu-18.04-bionic
...
```
```
root@Service1:/usr/share/weewx/user# grep Version: rtcr.py
Version: 0.2.3                                          Date: 9 March 2020
```
I've just grabbed the rtcr.py as mentioned in issue #3 and have done the replacement.  I'll see how it goes.

**Comment by gjr80** [comment]
Ok. At the very least it should give a more informative error trace. If it does produce an error could you please post the new error trace. Would also help to know what station you have and what driver you are using

**Comment by jkhuon** [comment]
I've got a WeatherFlow station and am using the WeatherFlow UDP driver.

**Comment by jkhuon** [comment]
Okay.  I have a crash trace.
```
Jun 12 00:00:03 Service1 weewx[19942] CRITICAL user.rtcr: Unexpected exception of type <type 'exceptions.KeyError'>
Jun 12 00:00:03 Service1 weewx[19942] ERROR user.rtcr: **** Traceback (most recent call last):
Jun 12 00:00:03 Service1 weewx[19942] ERROR user.rtcr: ****   File "/usr/share/weewx/user/rtcr.py", line 811, in run
Jun 12 00:00:03 Service1 weewx[19942] ERROR user.rtcr: ****     self.process_packet(_package['payload'])
Jun 12 00:00:03 Service1 weewx[19942] ERROR user.rtcr: ****   File "/usr/share/weewx/user/rtcr.py", line 837, in process_packet
Jun 12 00:00:03 Service1 weewx[19942] ERROR user.rtcr: ****     self.buffer.start_of_day_reset()
Jun 12 00:00:03 Service1 weewx[19942] ERROR user.rtcr: ****   File "/usr/share/weewx/user/rtcr.py", line 2295, in start_of_day_reset
Jun 12 00:00:03 Service1 weewx[19942] ERROR user.rtcr: ****     self[obs].day_reset()
Jun 12 00:00:03 Service1 weewx[19942] ERROR user.rtcr: **** KeyError: 'appTemp'
Jun 12 00:00:03 Service1 weewx[19942] CRITICAL user.rtcr: Thread exiting. Reason: 'appTemp'

```

**Comment by gjr80** [comment]
Thanks. That gives me enough to put a simple one line patch in place later today to avoid the error and stop the thread dying, unfortunately that will (likely) mean your clientraw.txt will only have the current appTemp; it will have no appTemp aggregates. I suspect I know why the error occurs, fixing that properly is going to take a little longer.

**Comment by jkhuon** [comment]
To be honest, my current consumer of clientraw.txt is my sprinkler system which I don't think really cares about appTemp aggregates.  That said, I'm sure others might.  A simple patch will suffice for now.  Thank you for following up on this.

**Comment by jkhuon** [comment]
Hmmm... so another thing I just noticed was that when I upgraded from weewx-3.9 to 4.1, I never bothered to migrate to the extended database schema (of which appTemp is defined) even though I redefined it in weewx.conf.

```
root@Service1:/etc/weewx# diff -cw weewx.conf weewx.conf.20200604143651
*** weewx.conf	2020-06-12 19:29:49.972498457 -0700
--- weewx.conf.20200604143651	2020-05-05 18:20:46.032954664 -0700
...

*** 591,600 ****
          # The name of the table within the database
          table_name = archive
          # The manager handles aggregation of data for historical summaries
!         manager = weewx.manager.DaySummaryManager
          # The schema defines the structure of the database.
          # It is *only* used when the database is created.
!         schema = schemas.wview_extended.schema
  
  ##############################################################################
  
--- 585,594 ----
          # The name of the table within the database
          table_name = archive
          # The manager handles aggregation of data for historical summaries
!         manager = weewx.wxmanager.WXDaySummaryManager
          # The schema defines the structure of the database.
          # It is *only* used when the database is created.
!         schema = schemas.wview.schema

```


I just did a "wee_database --reconfigure" and restarted with the new database.  I'll let you know if rtcr crashes tonight.

**Comment by gjr80** [comment]
Bit of a long story but I don't believe your db schema is part of the issue. What I believe is going on is that the Weatherflow station is what we call a partial packet station, ie the loop packets emitted by the driver do not necessarily contain all obs. `appTemp` is calculated by WeeWX provided `outTemp`, `outHumidity` and `windSpeed` are available. Since the Weatherflow loop packets do not necessarily include all three `appTemp` pre-requisites when the first loop packet is seen WeeWX does not calculate `appTemp` and add it to the loop packet. (it will be added to the archive record though as WeeWX will almost always certainly see some `outTemp`, `outHumidity` and `windSpeed` data throughout the archive period, it will also eventually be added to loop packets as rtcr maintains a small loop packet cache to support partial packets stations). Hold that thought.

In order to be able to provide aggregates (largely highs and lows) that include loop data rtcr maintains records of these aggregates for a limited set of obs. Some of these aggregates need to be reset at midnight. Unfortunately, the way I coded the object that stores these aggregates is that it sets up bins for each obs of interest (`appTemp` is one) that it sees in the first loop packet it receives. Because `appTemp` likely won't exist in the first loop packet received it is quite likely a bin will not be allocated for `appTemp`. The midnight reset resets all bins that rtcr might use (which is different to the bins rtcr actually did use), it tries to reset the `appTemp` bin but it does not exist and the error occurs.

The simple fix is to only reset the bins that exist and that is what I have done now. The long term  fix is to allow the bins to be dynamically created when a new obs of interest is first seen.

**Comment by gjr80** [comment]
Have applied the quick fix to `rtcr.py`, have bumped the version to 0.3.0a2 (you will find the version number at line 246 in `rtcr.py`). You should be able to use the exact same steps to download and use the updated `rtcr.py`:

1. move aside your existing `rtcr.py`:
```
$ mv /usr/share/weewx/user/rtcr.py /usr/share/weewx/user/rtcr_orig.py
```
2. download the new `rtcr.py` in place of your old:
```
$ wget -P /usr/share/weewx/user https://raw.githubusercontent.com/gjr80/weewx-realtime_clientraw/python3/bin/user/rtcr.py
```
3. restart WeeWX

**Comment by jkhuon** [comment]
> Bit of a long story but I don't believe your db schema is part of the issue. 

Ahhh... I get it.  So it's not a matter of trying to reference a database field that didn't exist as part of the schema as it is with attempting to reference an in-memory structure that hasn't yet been created due to the loop packet not exposing a reason to create it in the first place... at least not yet.  Thank you for the explanation.

I've downloaded and applied rtcr-0.3.0a2.  I'll monitor tonight for either a crash or lack thereof.

**Comment by jkhuon** [comment]
Midnight came and went and no signs of a crash.  Looks like clientraw.txt is continually being generated.
```
root@Service1:/usr/share/weewx/user# ls -l /var/www/html/weewx/clientraw.txt 
-rw-r--r-- 1 root root 778 Jun 13 00:04 /var/www/html/weewx/clientraw.txt
root@Service1:/usr/share/weewx/user# ls -l /var/www/html/weewx/clientraw.txt 
-rw-r--r-- 1 root root 778 Jun 13 00:06 /var/www/html/weewx/clientraw.txt
```

**Comment by jkhuon** [comment]
A second midnight rollover and everything is still running normally.  I'm okay with closing this issue.
