### ISSUE TITLE
Support for Weewx 4.1.1 and Python3?

### ISSUE THREAD

**Issue by terhoy** [gjr80/weewx-realtime_clientraw#5]
Hi,

I recently upgraded my Weewx installation to version 4.1.1 and switched to Python 3.5.3. Then I installed weewx-realtime_clientraw addon.

It looks like this version, 0.2.3, does not support Python3 and Weewx 4.1.1. I’d made some adjustments to the code (using 2to3 tool) and it runs without errors.

Regards, Terje

[rtcr.zip](https://github.com/gjr80/weewx-realtime_clientraw/files/5114825/rtcr.zip)

**Comment by magnum61** [comment]
Hi,

i was running in the same trap today. 
With your file it is running without issues, thanks for your efforts

Uwe

**Comment by magnum61** [comment]
quick update: I have the issue documented here:

https://github.com/gjr80/weewx-realtime_clientraw/issues/1

How to fix?
I ran a comparison of the file with yours, only the changed from your side are in, so it should work, but it does not

**Comment by bernardt60** [comment]
Hi,

I installed this version 0.2.3 and after these modifications :

[issues.hopefully.solved.txt](https://github.com/gjr80/weewx-realtime_clientraw/files/12468877/issues.hopefully.solved.txt)

I have this " Unexpected exception of type <class 'AttributeError'>:"
![exception](https://github.com/gjr80/weewx-realtime_clientraw/assets/143552443/61770705-281c-4dc2-a491-b50293e11a15)

Have you an idea how to solve this exception ?
Thanks
Best regards

**Comment by gjr80** [comment]
My apologies that this repo was neglected, since the Realtime clientraw service is mainly used to support the Saratoga Weather Website templates the Realtime clientraw service was rolled into the [`WeeWX-Saratoga extension`](https://github.com/gjr80/weewx-saratoga) repo back in 2021 and all subsequent development of the Realtime clientraw service has occurred in the WeeWX-Saratoga extension repo.

Whilst I would prefer to have the Realtime clientraw service code base exist in one repo only, I appreciate that some users may wish to install the Realtime clientraw service only without all of the extras included in the `WeeWX-Saratoga extension`. So I have decided to maintain both this and the `WeeWX-Saratoga extension` repos and synchronise the Realtime clientraw service code base between the two repos.

Please use the latest release v0.3.7, upgrading will be a simple case of installing the new version over the old. Probably worth doing a check of the `[RealtimeClientraw]` stanza in `weewx.conf` post-upgrade to make sure everything is as expected. Note that if using the `wee_extension` installer a copy of your pre-install/upgrade `weewx.conf` is automatically saved as `weewx.conf.YYYYmmddHHMMSS`.
